app:
  name: urlshort
  port: ":4444"
  db:
    postgres:
      dbhost: [IP_ADDRESS]
      dbuser: postgres
      dbpassword: postgres
      dbname: postgres
    redis:
      host: [IP_ADDRESS]
      port: 6379
